package ccf.domain.standard;

public enum StandardStatus {
    STANDARD_DISABLED,
    STANDARD_INITIALIZED_NO_DOMAINS,
    STANDARD_INITIALIZED_NO_DIMENSIONS,
    STANDARD_INITIALIZED_DIMENSIONS,
    STANDARD_INITIALIZED_TAXONOMIES,
    STANDARD_INITIALIZED_TAXONOMY_VERSIONS,
    STANDARD_INITIALIZED_TAXONOMY_ROWS,
    STANDARD_INITIALIZED
}

